apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: atos
  name: madapi-api
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get","create",delete,"describe","log", "list", "watch"]
